### ISSUE TITLE
Libretro core not loading Download from googleplay store

### ISSUE THREAD

**Issue by lt1023** [Swordfish90/Lemuroid#961]
Libretro core not loading

and rebuild source
err：StrictMode policy violation; ~duration=81 ms: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1661)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8378)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                                                                                                    	at java.io.File.exists(File.java:813)
                                                                                                    	at android.app.ContextImpl.getDataDir(ContextImpl.java:3197)
                                                                                                    	at android.app.ContextImpl.getFilesDir(ContextImpl.java:825)
                                                                                                    	at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:287)
                                                                                                    	at com.swordfish.libretrodroid.GLRetroViewData.<init>(GLRetroViewData.kt:27)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.initializeRetroGameView(BaseGameActivity.kt:345)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.access$initializeRetroGameView(BaseGameActivity.kt:103)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1061)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1057)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
2024-10-15 14:32:57.870  6494-6494  StrictMode              com.swordfish.lemuroid.debug         D  StrictMode policy violation; ~duration=81 ms: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1661)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8378)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                                                                                                    	at java.io.File.exists(File.java:813)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:791)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:782)
                                                                                                    	at android.app.ContextImpl.getFilesDir(ContextImpl.java:827)
                                                                                                    	at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:287)
                                                                                                    	at com.swordfish.libretrodroid.GLRetroViewData.<init>(GLRetroViewData.kt:27)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.initializeRetroGameView(BaseGameActivity.kt:345)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.access$initializeRetroGameView(BaseGameActivity.kt:103)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1061)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1057)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
2024-10-15 14:32:57.871  6494-6494  StrictMode              com.swordfish.lemuroid.debug         D  StrictMode policy violation; ~duration=81 ms: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1661)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8378)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                                                                                                    	at java.io.File.exists(File.java:813)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:791)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:782)
                                                                                                    	at android.app.ContextImpl.getFilesDir(ContextImpl.java:827)
                                                                                                    	at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:287)
                                                                                                    	at com.swordfish.libretrodroid.GLRetroViewData.<init>(GLRetroViewData.kt:28)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.initializeRetroGameView(BaseGameActivity.kt:345)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.access$initializeRetroGameView(BaseGameActivity.kt:103)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1061)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1057)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
2024-10-15 14:32:57.873  6494-6494  StrictMode              com.swordfish.lemuroid.debug         D  StrictMode policy violation; ~duration=44 ms: android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1661)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:269)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8387)
                                                                                                    	at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:331)
                                                                                                    	at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:889)
                                                                                                    	at dalvik.system.DexPathList.findLibrary(DexPathList.java:594)
                                                                                                    	at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:371)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1056)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at com.swordfish.libretrodroid.LibretroDroid.<clinit>(LibretroDroid.java:25)
                                                                                                    	at com.swordfish.libretrodroid.GLRetroView$onCreate$1.invoke(GLRetroView.kt:86)
                                                                                                    	at com.swordfish.libretrodroid.GLRetroView$onCreate$1.invoke(GLRetroView.kt:84)
                                                                                                    	at com.swordfish.libretrodroid.GLRetroView.catchExceptions(GLRetroView.kt:343)
                                                                                                    	at com.swordfish.libretrodroid.GLRetroView.onCreate(GLRetroView.kt:84)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:225)
                                                                                                    	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:199)
                                                                                                    	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:190)
                                                                                                    	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:40)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.initializeRetroGameView(BaseGameActivity.kt:380)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity.access$initializeRetroGameView(BaseGameActivity.kt:103)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1061)
                                                                                                    	at com.swordfish.lemuroid.app.shared.game.BaseGameActivity$loadGame$3.emit(BaseGameActivity.kt:1057)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$2.emit(Errors.kt:158)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by lt1023** [comment]
hhh，i resolve it。the author is funny！！！
